# Generated by Django 6.0.5 on 2026-05-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=100)),
                ('shift_date', models.DateField()),
                ('shift_type', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10)),
                ('equipment_status', models.TextField(blank=True)),
                ('incidents', models.TextField(blank=True)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-shift_date'],
            },
        ),
    ]
